name: Windows-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Configure CMake
        # We use ninja-build
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 17 2022"
      - name: Build
        # Build rioring library and unit test binary
        run: |
          cmake --build ${{github.workspace}}\build --target rioring
          cmake --build ${{github.workspace}}\build --target BasicTest
      - name: Test
        # Using google test
        # The basic test is [io start -> prepare client -> echo packet between server and client -> io stop]
        run: |
          ${{github.workspace}}\bin\BasicTest.exe
