name: Linux-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-linux:
    # ubuntu-22.04 has liburing-dev.
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install build toolchain
      run: |
        sudo apt install -y ninja-build liburing-dev
      shell: bash
    - name: Configure CMake
      # We use ninja-build
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      env:
        CC: gcc-11
        CXX: g++-11

    - name: Build
      # Build rioring library and unit test binary
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target rioring
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target BasicTest

    - name: Test
      # Using google test
      # The basic test is [io start -> prepare client -> echo packet between server and client -> io stop]
      run: |
        ${{github.workspace}}/bin/BasicTest

